#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'

echo '🔍Type checking your code with TypeScript🔍'

# Type check
yarn type-check ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check type defintition 🔨❌
          please validate your type and try commit again.';
    false;
)

echo 'type-check: OK'

echo '🔍Linting your code with ESLint🔍'

# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged